name: Takeda Demo 1 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      with:
        java-version: '11'
    - name: Run the Maven verify phase
      run: mvn test
